name: 'Infragenie'
description: 'Commit and push to the repository the changes made to the architecture of the system in a diagram'
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
